categories = [
    "Quron Karim 🌙",
    "Taklif yuborish 📝"
    # "Hadis 📚",
    # "Payg’ambarlar Tarixi 🕋",
    # "Namoz o’qish ✨",
    # "Duolar va Salovatlar 🤲",
    # "Donation 💳"
    ]

quroni_karim = [
    "Audio 🎧",
    "Matn 📝",
    "Orqaga 🔙"]

audio = [
    "O'zbek tilidagi Qur'oni Karim 🇺🇿",
    "Arab tilidagi Qur'oni Karim 🇸🇦",
    "🔙 Orqaga"]

matn = [
    "O'zbek tilidagi Qur'oni Karim (matn) 🇺🇿",
    "Arab tilidagi Qur'oni Karim (matn) 🇸🇦",
    "Arab (lotin) tilidagi Qur'oni Karim (matn) 🇸🇦",
    "🔙 Orqaga"]

quron_suralar = [
    "1.Fotiha",
    "2.Baqara",
    "3.Oli Imron",
    "4.Niso",
    "5.Moida",
    "6.An’om",
    "7.A’rof",
    "8.Anfol",
    "9.Tavba",
    "10.Yunus",
    "11.Hud",
    "12.Yusuf",
    "13.Ra’d",
    "14.Ibrohim",
    "15.Hijr",
    "16.Nahl",
    "17.Isro",
    "18.Kahf",
    "19.Maryam",
    "20.Toha",
    "21.Anbiyo",
    "22.Haj",
    "23.Mu'minun",
    "24.Nur",
    "25.Furqon",
    "26.Shu’aro",
    "27.Naml",
    "28.Qasas",
    "29.Ankabut",
    "30.Rum",
    "31.Luqmon",
    "32.Sajda",
    "33.Ahzob",
    "34.Saba’",
    "35.Fotir",
    "36.Yosin",
    "37.Soffat",
    "38.Sod",
    "39.Zumar",
    "40.G’ofir",
    "41.Fussilat",
    "42.Sho’ro",
    "43.Zuxruf",
    "44.Duxon",
    "45.Josiya",
    "49.Ahqof",
    "47.Muhammad",
    "48.Fath",
    "49.Hujurot",
    "50.Qof",
    "51.Zoriyot",
    "52.Tur",
    "53.Najm",
    "54.Qamar",
    "55.Rahmon",
    "56.Voqea",
    "57.Hadid",
    "58.Mujodala",
    "59.Hashr",
    "60.Mumtahana",
    "61.Saf",
    "62.Jum’a",
    "63.Munofiqun",
    "64.Tag’obun",
    "65.Taloq",
    "66.Tahrim",
    "67.Mulk",
    "68.Qalam",
    "69.Haaqqa",
    "70.Maori",
    "71.Nuh",
    "72.Jin",
    "73.Muzzammil",
    "74.Muddassir",
    "75.Qiyomat",
    "76.Inson",
    "77.Mursalot",
    "78.Naba'",
    "79.Nazi’at",
    "80.Abasa",
    "81.Takvir",
    "82.Infitor",
    "83.Mutoffifin",
    "84.Inshiqoq",
    "85.Buruj",
    "86.Toriq",
    "87.A’lo",
    "88.G’oshiya",
    "89.Fajr",
    "90.Balad",
    "91.Shams",
    "92.Layl",
    "93.Zuho",
    "94.Sharh",
    "95.Tiyn",
    "96.Alaq",
    "97.Qadr",
    "98.Bayyina",
    "99.Zalzala",
    "100.Odiyat",
    "101.Qori’a",
    "102.Takosur",
    "103.Asr",
    "104.Humaza",
    "105.Fil",
    "106.Quraysh",
    "107.Mo’un",
    "108.Kavsar",
    "109.Kofirun",
    "110.Nasr",
    "111.Masad",
    "112.Ixlos",
    "113.Falaq",
    "114.Nos"
]

uzbek_audio_btn = [
    "uzbek_audio",
    "preview",
    "page",
    "next",
    "back_categories"
]

arab_audio_btn = [
    "arab_audio",
    "preview_arab",
    "page_arab",
    "next_arab",
    "back_categories"
]

uzbek_matn_btn = [
    "uzbek_matn",
    "uzbek_preview",
    "uzbek_page",
    "uzbek_next",
    "uzbek_back"]

arab_matn_btn = [
    "arab_matn",
    "arab_preview",
    "arab_page",
    "arab_next",
    "arab_back"]

arab_matn_lotin_btn = [
    "arab_lotin_matn",
    "arab_lotin_preview",
    "arab_lotin_page",
    "arab_lotin_next",
    "arab_lotin_back"]